import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,html}",
  ],
  theme: {
    extend: {
      colors: {
        // Cyber-Industrial Minimalist palette (new design system).
        // See new_theme/technical_precision/DESIGN.md for the canonical spec.
        "primary": "#9cefff",
        "primary-container": "#00daf3",
        "primary-fixed": "#9cefff",
        "primary-fixed-dim": "#01daf3",
        "on-primary": "#00363d",
        "on-primary-container": "#005b67",
        "on-primary-fixed": "#001f24",
        "on-primary-fixed-variant": "#004f58",
        "inverse-primary": "#006875",
        "secondary": "#b9c8dd",
        "secondary-container": "#39485a",
        "secondary-fixed": "#d4e4fa",
        "secondary-fixed-dim": "#b9c8dd",
        "on-secondary": "#233142",
        "on-secondary-container": "#a7b6cb",
        "on-secondary-fixed": "#0d1d2c",
        "on-secondary-fixed-variant": "#39485a",
        "tertiary": "#a1eefd",
        "tertiary-container": "#85d2e1",
        "tertiary-fixed": "#a2effe",
        "tertiary-fixed-dim": "#85d2e1",
        "on-tertiary": "#00363e",
        "on-tertiary-container": "#005b67",
        "on-tertiary-fixed": "#001f24",
        "on-tertiary-fixed-variant": "#004e59",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "surface": "#071518",
        "surface-dim": "#071518",
        "surface-bright": "#2d3c3e",
        "surface-main": "#051424",
        "surface-variant": "#29373a",
        "surface-tint": "#01daf3",
        "surface-container-lowest": "#031013",
        "surface-container-low": "#101e20",
        "surface-container": "#142224",
        "surface-container-high": "#1c2b3c",
        "surface-container-highest": "#29373a",
        "on-surface": "#d6e5e8",
        "on-surface-variant": "#bac9cc",
        "on-surface-muted": "#bac9cc",
        "inverse-surface": "#d6e5e8",
        "inverse-on-surface": "#253335",
        "outline": "#859396",
        "outline-variant": "#3b494c",
        "background": "#071518",
        "on-background": "#d6e5e8",
        "glass-bg": "rgba(18, 33, 49, 0.7)",
        "glass-border": "rgba(59, 73, 76, 0.3)",
        "success-glow": "#00daf3",

        // Legacy keys retained for views not yet migrated. Removed in
        // Phase 6 of the theme migration.
        "primary-dim": "#00a3ad",
        "accent-red": "#ff003c",
        "background-light": "#f6f7f8",
        "background-dark": "#071518",
        "background-panel": "#142224",
        "glass": "rgba(255, 255, 255, 0.03)",
      },
      fontFamily: {
        "display-lg": ["Inter", "system-ui", "sans-serif"],
        "headline-md": ["Inter", "system-ui", "sans-serif"],
        "title-sm": ["Inter", "system-ui", "sans-serif"],
        "body-base": ["Inter", "system-ui", "sans-serif"],
        "body-sm": ["Inter", "system-ui", "sans-serif"],
        "label-technical": ["JetBrains Mono", "ui-monospace", "monospace"],
        "label-micro": ["JetBrains Mono", "ui-monospace", "monospace"],
        // Legacy aliases — still used by unmigrated views. Phase 6 cleanup.
        "display": ["Inter", "Manrope", "system-ui", "sans-serif"],
        "mono": ["JetBrains Mono", "Space Mono", "ui-monospace", "monospace"],
      },
      fontSize: {
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "title-sm": ["18px", { lineHeight: "24px", fontWeight: "500" }],
        "body-base": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-technical": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-micro": ["10px", { lineHeight: "14px", letterSpacing: "0.1em", fontWeight: "500" }],
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "gutter": "1rem",
        "sidebar-width": "72px",
        "thread-list-width": "360px",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px",
      },
      boxShadow: {
        "neon": "0 0 10px rgba(0, 240, 255, 0.3), 0 0 20px rgba(0, 240, 255, 0.1)",
        "glitch": "2px 0 #ff003c, -2px 0 #00f0ff",
        "tactile-glow": "0 0 20px rgba(1, 218, 243, 0.3)",
        "status-glow-cyan": "0 0 12px rgba(1, 218, 243, 0.6)",
      },
    },
  },
  plugins: [
    forms,
    containerQueries,
  ],
};
